version: '3.8'

services:
  api-platform:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ip"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 